name: Deploy

on:
  - workflow_dispatch

concurrency:
  group: terra

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: terra
      url: https://tabeblebase.lichess.ovh
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: lila-tablebase
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy-host
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
      - name: Deploy via SSH
        run: cat lila-tablebase | ssh deploy-host "mv /usr/local/bin/lila-tablebase /usr/local/bin/lila-tablebase.bak && cat - > /usr/local/bin/lila-tablebase && systemctl restart lila-tablebase"
